### ISSUE TITLE
Homage "Products By Canswe"

### ISSUE THREAD

**Issue by gregdaynes** [Canary-PrintDesign/canswe#10]

**Comment by adamish717** [comment]
I'd like to make a major change from the design proof on this area.

Design shows boxes, but if we follow those links through to their conclusion, it basically just links to the "all our products" page, which seems silly.

Lets keep the top area the same, and instead of product groups, lets have Poly Pro 3600 and the Nylon Poly Pro and have them ribbon'd with a "Top Seller" across a top corner or something.

There's probably a better idea out there, but that's where I'm at right now

**Comment by LouisRitchie** [comment]
Here's my first pass at this: https://github.com/Canary-PrintDesign/canswe/pull/45
